USE facturador;

      -- STORED PROCEDURES I
DROP PROCEDURE IF EXISTS PS_INSERTDATOS_PRODUCTOS ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_INSERTDATOS_PRODUCTOS 
(IN MARCA_P VARCHAR(250), IN MODELO_P VARCHAR(250), IN PRECIO_P INT, IN SERIAL_NUMBER_P VARCHAR(250) , IN PRODUCTO_DISPONIBLE_p INT  ) 
--  CREAMOS EL SP PARA INSERTAR DATOS EN LAS TABLAS Y DEFINIMOS QUE TIPOS DE DATOS VAMOS A INGRESAR
begin
	INSERT INTO productos (Marca,Modelo,Precio,Serial_number,Producto_disponible)	
    -- INGRESAMOS LOS DATOS SELECCIONAMOS LA TABLA Y DEFINIMOS EN QUE CAMPOS VAMOS A INGRESAR ESOS DATOS
    VALUES (MARCA_P,	MODELO_P, PRECIO_P, SERIAL_NUMBER_P,	PRODUCTO_DISPONIBLE_p) ; -- DEFINIMOS QUE VALORES INGRESAMOS DE LOS DATOS QUE DEFINIMOS
 end //
 DELIMITER ;


			-- STORED PROCEDURES II

        
DROP PROCEDURE IF EXISTS PS_DELET_VALUES_PRODUCTOS ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_DELET_VALUES_PRODUCTOS (IN ID_PRODUCTO_P INT)--  CREAMOS EL SP PARA BORRAR VALORES DE LAS TABLAS
begin
DELETE FROM productos -- SELECIONAMOS LA TABLA QUE QUEREMOS BORRAR VALORES
WHERE ID_PRODUCTO = ID_PRODUCTO_P ; -- DEFINIMOS QUE SI EL VALOR ID_PRODUCTO O EL QUE QUERRAMOS BORRAR, ES IGUAL AL DATO INGRESADO BORRA TODOS LOS CAMPOS DE ESE CAMPO
 end //
 DELIMITER ;


		-- STORED PROCEDURES III
        
SELECT * FROM productos;
DROP PROCEDURE IF EXISTS PS_ORDER_PRODUCTOS_ASC_DES ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_ORDER_PRODUCTOS_ASC_DES (IN ORDENAR_POR_P VARCHAR(250), IN ORDERBY_DES_ASC_P  VARCHAR(250) ) --  CREAMOS EL SP PARA INGRESAR LOS DATOS QUE VAMOS A ORDENAR
begin
SET @ORDENAR = CONCAT('SELECT * FROM Productos ORDER BY',' ',ORDENAR_POR_P,' ',ORDERBY_DES_ASC_P); -- ACA CONCATENAMOS DE COMO VAMOS A ORDENAR LOS DATOS Y DE QUE TABLA LA SACAMOS 
PREPARE Param_ORDENAR FROM @ORDENAR; -- ACA PREPARAMOS LA SENTENCIA @ORDENAR 
EXECUTE Param_ORDENAR; -- CON EL EXECUTE PODEMOS EJECUTAR EL PROCEDIMIENTO ALMACENADO EN @ORDENAR
DEALLOCATE PREPARE Param_ORDENAR; -- ACA LA USAMOS PARA DESASIGNAR LA DECLARACION @ORDENAR QUE LA PRODUCIMOS CON EL PREPARE
 end //
SET @ORDENAR_POR_P = 'PRECIO';  -- HACEMOS EL UPDATE DE LOS VALORES DECLARADOS EN LA CREACION DE LA SP
SET @ORDERBY_DES_ASC_P = 'DESC';-- HACEMOS EL UPDATE DE LOS VALORES DECLARADOS EN LA CREACION DE LA SP
 delimiter ;
 

     -- STORED PROCEDURES IV
DROP PROCEDURE IF EXISTS PS_INSERTDATOS_CLIENTES ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_INSERTDATOS_CLIENTES (IN NOMBRE_P VARCHAR(250), IN APELLIDO_P VARCHAR(250), IN MAIL_P VARCHAR(250), IN DNI_P INT, IN PROVINCIA_P VARCHAR (250), IN LOCALIDAD_P VARCHAR (250), IN TELEFONO_P INT) --  CREAMOS EL SP PARA INSERTAR DATOS EN LAS TABLAS Y DEFINIMOS QUE TIPOS DE DATOS VAMOS A INGRESAR
begin
	INSERT INTO cliente (NOMBRE,APELLIDO,MAIL,DNI,PROVINCIA,LOCALIDAD,TELEFONO)	-- INGRESAMOS LOS DATOS SELECCIONAMOS LA TABLA Y DEFINIMOS EN QUE CAMPOS VAMOS A INGRESAR ESOS DATOS
    VALUES (NOMBRE_P,	APELLIDO_P,	MAIL_P,	DNI_P,	PROVINCIA_P,	LOCALIDAD_P, TELEFONO_P) ; -- DEFINIMOS QUE VALORES INGRESAMOS DE LOS DATOS QUE DEFINIMOS
 end //
 DELIMITER ;


			-- STORED PROCEDURES V
DROP PROCEDURE IF EXISTS PS_DELET_VALUES_CLIENTES ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_DELET_VALUES_CLIENTES (IN ID_CLIENTE_P INT)--  CREAMOS EL SP PARA BORRAR VALORES DE LAS TABLAS
begin
DELETE FROM CLIENTEBK -- SELECIONAMOS LA TABLA QUE QUEREMOS BORRAR VALORES
WHERE ID_CLIENTE = ID_CLIENTE_P ; -- DEFINIMOS QUE SI EL VALOR ID_PRODUCTO O EL QUE QUERRAMOS BORRAR, ES IGUAL AL DATO INGRESADO BORRA TODOS LOS CAMPOS DE ESE CAMPO
 end //
 DELIMITER ;

			-- STORED PROCEDURES VI
DROP PROCEDURE IF EXISTS PS_Gar ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_Gar 
(IN ID_Recibo INT, IN ID_Producto INT, IN ID_Provincias INT, IN ID_Cliente INT , IN ID_Localidad INT, IN Fecha_de_compra int,IN Inicio_Garantia INT, IN Fin_garantia INT  ) 
--  CREAMOS EL SP PARA INSERTAR DATOS EN LAS TABLAS Y DEFINIMOS QUE TIPOS DE DATOS VAMOS A INGRESAR
begin
	INSERT INTO garantia (Recibo_ID,Producto_ID,Provincias_ID,Cliente_ID,Cliente_ID,Localidad_ID,Fecha_de_Compra,Inicio_Garantia,Fin_garantia)	
    -- INGRESAMOS LOS DATOS SELECCIONAMOS LA TABLA Y DEFINIMOS EN QUE CAMPOS VAMOS A INGRESAR ESOS DATOS
    VALUES (ID_Recibo,	ID_Producto, ID_Provincias, ID_Cliente,	ID_Localidad, Fecha_de_compra, Inicio_Garantia, Fin_garantia) ; -- DEFINIMOS QUE VALORES INGRESAMOS DE LOS DATOS QUE DEFINIMOS
 end //
 DELIMITER ;
 

			-- STORED PROCEDURES VII
DROP PROCEDURE IF EXISTS PS_Env ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_Env 
(IN ID_DIR INT, IN ID_CLI INT, IN Fecha_de_Envio int,IN Estado_Entrega INT) 
--  CREAMOS EL SP PARA INSERTAR DATOS EN LAS TABLAS Y DEFINIMOS QUE TIPOS DE DATOS VAMOS A INGRESAR
begin
INSERT INTO envio (Direccion_ID,Cliente_ID,Fecha_de_envio,Estado_Entrega)	-- INGRESAMOS LOS DATOS SELECCIONAMOS LA TABLA Y DEFINIMOS EN QUE CAMPOS VAMOS A INGRESAR ESOS DATOS
VALUES (ID_DIR,	ID_CLI, Fecha_de_Envio, Estado_Entrega) ; -- DEFINIMOS QUE VALORES INGRESAMOS DE LOS DATOS QUE DEFINIMOS
 end //
 DELIMITER ;