use facturadorbk;
      -- STORED PROCEDURES I
	SELECT * FROM PRODUCTOBK; 
DROP PROCEDURE IF EXISTS PS_INSERTDATOS ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_INSERTDATOS_PRODUCTOS (IN MARCA_P VARCHAR(250), IN MODELO_P VARCHAR(250), IN SERIAL_NUMBER_P VARCHAR(250), IN PRECIO_P INT, IN PRODUCTO_DISPONIBLE_p INT  ) --  CREAMOS EL SP PARA INSERTAR DATOS EN LAS TABLAS Y DEFINIMOS QUE TIPOS DE DATOS VAMOS A INGRESAR
begin
	INSERT INTO PRODUCTOBK (Marca,Modelo,Serial_number,Precio,Producto_disponible)	-- INGRESAMOS LOS DATOS SELECCIONAMOS LA TABLA Y DEFINIMOS EN QUE CAMPOS VAMOS A INGRESAR ESOS DATOS
    VALUES (MARCA_P,	MODELO_P,	SERIAL_NUMBER_P,	PRECIO_P,	PRODUCTO_DISPONIBLE_p) ; -- DEFINIMOS QUE VALORES INGRESAMOS DE LOS DATOS QUE DEFINIMOS
 end //
 delimiter ;
 
CALL PS_INSERTDATOS_PRODUCTOS('XBOX','JOSTYCK','M1106906007',30500,1); -- LLAMAMOS AL SP E INGRESAMOS LOS VALORES

			-- STORED PROCEDURES II

        
SELECT * FROM PRODUCTOBK;
DROP PROCEDURE IF EXISTS PS_DELET_VALUES_PRODUCTOS ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_DELET_VALUES_PRODUCTOS (IN ID_PRODUCTO_P INT)--  CREAMOS EL SP PARA BORRAR VALORES DE LAS TABLAS
begin
DELETE FROM PRODUCTOBK -- SELECIONAMOS LA TABLA QUE QUEREMOS BORRAR VALORES
WHERE ID_PRODUCTO = ID_PRODUCTO_P ; -- DEFINIMOS QUE SI EL VALOR ID_PRODUCTO O EL QUE QUERRAMOS BORRAR, ES IGUAL AL DATO INGRESADO BORRA TODOS LOS CAMPOS DE ESE CAMPO
 end //
 delimiter ;
 
	CALL PS_DELET_VALUES (9); -- LLAMAMOS A LA SP Y DEFINIMOS QUE DATO QUEREMOS BORRAR 


		-- STORED PROCEDURES III
        
SELECT * FROM PRODUCTOBK;
DROP PROCEDURE IF EXISTS PS_ORDER_PRODUCTOS_ASC_DES ; -- BORRAMOS EL SP SI EXISTE 
delimiter //
CREATE PROCEDURE PS_ORDER_PRODUCTOS_ASC_DES (IN ORDENAR_POR_P VARCHAR(250), IN ORDERBY_DES_ASC_P  VARCHAR(250) ) --  CREAMOS EL SP PARA INGRESAR LOS DATOS QUE VAMOS A ORDENAR
begin
SET @ORDENAR = CONCAT('SELECT * FROM PRODUCTOBK ORDER BY',' ',ORDENAR_POR_P,' ',ORDERBY_DES_ASC_P); -- ACA CONCATENAMOS DE COMO VAMOS A ORDENAR LOS DATOS Y DE QUE TABLA LA SACAMOS 
PREPARE Param_ORDENAR FROM @ORDENAR; -- ACA PREPARAMOS LA SENTENCIA @ORDENAR 
EXECUTE Param_ORDENAR; -- CON EL EXECUTE PODEMOS EJECUTAR EL PROCEDIMIENTO ALMACENADO EN @ORDENAR
DEALLOCATE PREPARE Param_ORDENAR; -- ACA LA USAMOS PARA DESASIGNAR LA DECLARACION @ORDENAR QUE LA PRODUCIMOS CON EL PREPARE
 end //
SET @ORDENAR_POR_P = 'PRECIO';  -- HACEMOS EL UPDATE DE LOS VALORES DECLARADOS EN LA CREACION DE LA SP
SET @ORDERBY_DES_ASC_P = 'DESC';-- HACEMOS EL UPDATE DE LOS VALORES DECLARADOS EN LA CREACION DE LA SP
 delimiter ;
 
CALL PS_ORDER_PRODUCTOS_ASC_DES ('PRODUCTO_DISPONIBLE','DESC')	-- (@ORDENAR_POR_P,@ORDERBY_DES_ASC_P) PORQUE PARAMETROS QUEREMOS ORDENARLOS Y EN QUE ESCALA SI DESCENDENTE O ASCENDENTE


