DROP SCHEMA IF EXISTS TRIGGERSS;
CREATE SCHEMA IF NOT EXISTS TRIGGERSS ;
USE TRIGGERSS;
DROP TABLE IF EXISTS `Clientebk`;
create table Clientebk(
ID_Cliente int  primary key not null auto_increment,
nombre varchar (1000) not null,
apellido varchar(1000) not null,
email varchar(1000) not null,
dni int unsigned not null,
provincia varchar(1000) not null,
localidad varchar(1000) not null
);
 DROP TABLE IF EXISTS LOG_CLIENTEBK ;
 CREATE TABLE IF NOT EXISTS LOG_CLIENTEBK
 (
ID_LOG_CLIENTEBK INT PRIMARY KEY AUTO_INCREMENT NOT NULL,-- PK
NOMBRE_ACCION VARCHAR(500), -- LA ACCION QUE SE COMETIO EN LA TABLA 
NOMBRE_TABLA VARCHAR(500), -- NOMBRE DE LA TABLA QUE SE VA A VIGILAR
USUARIO VARCHAR(500), -- QUE USUARIO MODIFICA LA TABLA PRINCIPAL
FECHA_DE_MODIFICACION DATE -- CUANDO SE MODIFICA LA TABLA
  );
  
   DROP TABLE IF EXISTS LOG_CLIENTEBK_2 ;
 CREATE TABLE IF NOT EXISTS LOG_CLIENTEBK_2
 (
ID_AUDITORIA_CLIENTEBK INT PRIMARY KEY AUTO_INCREMENT NOT NULL,-- PK
NOMBRE_ACCION VARCHAR(500), -- LA ACCION QUE SE COMETIO EN LA TABLA 
NOMBRE_TABLA VARCHAR(500), -- NOMBRE DE LA TABLA QUE SE VA A VIGILAR
USUARIO VARCHAR(500), -- QUE USUARIO MODIFICA LA TABLA PRINCIPAL
FECHA_DE_MODIFICACION DATE, -- CUANDO SE MODIFICA LA TABLA
CAMPONUEVO_CAMPOVIEJO VARCHAR(5000), -- CAMPOS ANTERIORES Y DESPUES DEL CAMBIO
DNI  INT UNSIGNED NOT NULL,
ID_CLIENTE INT NOT NULL
  );

DROP TRIGGER IF EXISTS TRG_CLIENTEBK_SEG_INSERT;
DELIMITER //
CREATE TRIGGER TRG_CLIENTEBK_SEG_INSERT AFTER INSERT ON TRIGGERSS.CLIENTEBK
FOR EACH ROW
BEGIN
INSERT INTO AUDITORIA_CLIENTEBK(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_DE_MODIFICACION)
VALUES ('INSERT', 'CLIENTEBK', CURRENT_USER(), NOW());
END //
DELIMITER ;

DROP TRIGGER IF EXISTS TRG_CLIENTEBK_SEG_INSERT2;
DELIMITER //
CREATE TRIGGER TRG_CLIENTEBK_SEG_INSERT2 AFTER INSERT ON TRIGGERSS.CLIENTEBK
FOR EACH ROW
BEGIN
INSERT INTO AUDITORIA_CLIENTEBK2(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_DE_MODIFICACION, CAMPONUEVO_CAMPOVIEJO, DNI, ID_CLIENTE)
VALUES ('INSERT', 'CLIENTEBK', CURRENT_USER(), NOW(), '', NEW.DNI, NEW.ID_CLIENTE);
END //
DELIMITER ;

DROP TRIGGER IF EXISTS TRG_CLIENTEBK_SEG_INSERT3;
DELIMITER //
CREATE TRIGGER TRG_CLIENTEBK_SEG_INSERT3 BEFORE UPDATE ON TRIGGERSS.CLIENTEBK
FOR EACH ROW
BEGIN
INSERT INTO AUDITORIA_CLIENTEBK2(NOMBRE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_DE_MODIFICACION, CAMPONUEVO_CAMPOVIEJO, DNI, ID_CLIENTE)
VALUES ('UPDATE', 'CLIENTEBK', CURRENT_USER(), NOW(), '', OLD.DNI, NEW.ID_CLIENTE);
END //
DELIMITER ;


DROP TRIGGER IF EXISTS TRG_CLIENTEBK_SEG_INSERT4;
DELIMITER //
CREATE TRIGGER TRG_CLIENTEBK_SEG_INSERT4 AFTER UPDATE ON TRIGGERSS.CLIENTEBK
FOR EACH ROW
BEGIN
INSERT INTO AUDITORIA_CLIENTEBK2(DNI, ID_CLIENTE, NOMBRE_ACCION, NOMBRE_TABLA, FECHA_DE_MODIFICACION)
VALUES ( CONCAT('CAMPO VIEJO :' , OLD.DNI, 'CAMPO NUEVO :' ,NEW.DNI), NEW.ID_CLIENTE, 'UPDATE', 'CLIENTEBK',  NOW() );
END //
DELIMITER ;

INSERT INTO clientebk(nombre,apellido,email,dni,provincia,localidad)VALUE
 ('Kevin','Ayala','kevin.eliasayala@gmail.com','43011615','Buenos Aires','Caseros'),
('Lautaro','Bazzola','lautaro.bazzola@gmail.com','39592309','Tierra del Fuego','Ushuaia'),
('Daniel','Matalone','daniel.matalone@gmail.com','32834933','Misiones','Iguazú'),
('Nicolas','Torres','torresnicolasezequiel23@outlook.com','41215267','Formosa','Las Lomitas');

SELECT *FROM AUDITORIA_CLIENTEBK;
SELECT *FROM AUDITORIA_CLIENTEBK2;
SELECT * FROM TRIGGERSS.CLIENTEBK;
UPDATE `TRIGGERSS`.`CLIENTEBK` SET `dni` = '123456789' WHERE (`ID_Cliente` = '55');
